### ISSUE TITLE
bible.php search box refined

### ISSUE THREAD

**Issue by nielsencs** [nielsencs/BibleStudyMan#9]
it's all a bit cluttered

- [x] lose some 'clear' buttons?
- [x] lose the two duplicate buttons at the top
- [x] change the 'Show More?' checkbox to inverted functionality with 'Specific phrase?'
- [x] move 'Words' section above (lose the word 'Words')

**Comment by marvinbarretto** [comment]
Would something like this work for the search box? <img width="542" alt="Screenshot 2020-04-23 18 11 40" src="https://user-images.githubusercontent.com/693388/80128742-01c8ab80-858e-11ea-8228-6c34126a7910.png">

**Comment by RuthieNielsen** [comment]
Sorry Marv I have only just realised that you did a mock-up but I have already done a couple so here they are! It looks like your one is a lot more like what @nielsencs wants! Mine is probably a bit too different haha!
![65B48942-0182-4D6E-BFBA-E06DB91537DD](https://user-images.githubusercontent.com/44913707/80135911-dac3a700-8598-11ea-8a82-8a6c95bb55a7.png)
![85A8D653-8CE2-4A4D-ADED-B88DC897220A](https://user-images.githubusercontent.com/44913707/80135913-dd260100-8598-11ea-948b-7ef51f8a44af.png)
![EC385BF9-C138-4310-974E-A15CD949CB76](https://user-images.githubusercontent.com/44913707/80135914-ddbe9780-8598-11ea-9ab5-03480ae60cde.png)

I also thought it might be worth pointing out that this could be a good resource for free icons! https://material.io/resources/icons

**Comment by nielsencs** [comment]
creating new issue from first comment 'change the 'Show More?' checkbox to inverted functionality with 'Specific phrase?'
